### PR TITLE
[Enhancement] 1.3.0 (perhaps)

### PR DESCRIPTION
**Pull request by prodzpod**
- Custom Repair Config
- Equipment Repair
- Boss/Lunar/Equipment Cost Config
- Void Lunar compat

it also adds Regenerating Scrap and Trophy Hunter's Tricorn for the default recipes, feel free to remove them if you think its too much lol

### CODE REVIEW

**Comment by viliger2** [comment]
Seems fine, I am guessing the idea behind replacing blacklist with repair list is to allow users themselves add repair pairs via config, especially for modded items. I don't see any issues outside of very minor code formatting.
Tricorn and Regenerating Scrap are fine as additions, I completely forgot about them.

**Comment by prodzpod** [comment]
hi since you didnt merge yet i squeezed in 1 extra feature.
blacklist was replaced because it would be redundant if people could just remove the entry.

**Comment by viliger2** [comment]
If you are adding multiple uses then might as well add limit to number of uses, like majority of vanilla shrines do.

**Comment by prodzpod** [comment]
alright, max uses it is (to be honest i was just avoiding it out of laziness). it's absolutely a janky hack though. please replace with more robust code once you're free.

**Comment by viliger2** [comment]
Max uses were clearly done in a rush, you are only increasing them on client for Picker, resulting in server not even knowing about them, which you don't even need to do, we can just send the message to client when we reach required number of uses to disable intractable. And for Purchase it is not done at all outside of zero check to make it infinite.
I am just gonna merge 1.3.0 commit, if you want to make a proper implementation of multiple uses you are free to do so, I am not gonna do it right now, maybe later.

**Pull request closed without merging**
